version: 0.2


phases:
  install:
   
    commands:
        # install npm
        - npm install
       
  build:
    commands:
        # run build script
        - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: build